### ISSUE TITLE
v9 roadmap (breaking)

### ISSUE THREAD

**Issue by davalapar** [davalapar/ruruDB#6]
## Rewrite in pure Javascript (since types were useless anyways)

- README
- Jest tests

## KVTable type checks

- Key
  - must only be non-empty strings and numbers
  - must not be objects or arrays or any other primitive values
- Value
  - must not be class-based instances

## Table and KVTable

- Type-check `database` parameter
- Prevent `new` instances? There must be a way instead for us to ensure the table exists, or create it if it does not exists.

## Table

- schemas 
 - creating a table will now require schema
  - upon load, items must be validated against schema
  - items failing validation should passed through `updateFn`
  - if validation fails again, we throw an error
  - inserted items must be validated against schema
  - we must have our own custom format distant from that of ajv (which is too complex)
  - db.initializeTable(schema, updateFn);
  - http://json-schema.org/specification.html
  - http://json-schema.org/latest/json-schema-validation.html#rfc.section.6.1
- Custom copy function using `Object.assign`
  - Must recursively check each parameter type
  - Must throw error on non-supported types
  - Items (or documents) should only contain valid contents
  - Top-level values must be valid primitive types
  - Nested object and array values must not have further nested values
- Record freezing using `Object.freeze`
  - https://github.com/substack/deep-freeze
  - https://github.com/snovakovic/js-flock/blob/master/src/internals/deep.js
- Optional boolean parameter for fetch functions, to return modifyable clones

## Query

- New methods
  - .cloneResults()
  - .hasResults()
  - .countResults()
- Method calls should check table schema first before doing anything
- Filter methods should do type-checks on item fields
- Filter methods should only apply if current filter is applicable on item field
- Filter methods should throw errors when not applicable on item field

## Watcher
- [ ] Watches values on Table / KVTable

## Messagepack for smaller / compact db file size
- [ ] converter between `*.rrdb` and `*.prrdb` files
- [ ] show warning when size is db is nearby pre-allocated buffer size limit

## Sorting Items thru Haversine Formula

- Useful in sorting items that have `[latitude, longitude]` array fields
- Output distance is in kilometers, convertible to miles
- [ ] https://www.movable-type.co.uk/scripts/latlong.html
- [ ] Query().ascendHaversine(field, lat, long);
- [ ] Query().descendHaversine(field, lat, long);

**Comment by davalapar** [comment]
#### Rewrite in pure Javascript (since types were useless anyways)

#### Table

- Custom copy function using `Object.assign`
  - Must recursively check each parameter type
  - Must throw error on non-supported types
  - Items (or documents) should only contain valid contents
  - Top-level values must be valid primitive types
  - Nested object and array values must not have further nested values
- Record freezing using `Object.freeze`
  - https://github.com/substack/deep-freeze
  - https://github.com/snovakovic/js-flock/blob/master/src/internals/deep.js
- Optional boolean parameter for fetch functions, to return modifyable clones

#### Query

- New methods
  - .cloneResults()
  - .hasResults()
  - .countResults()
- Method calls should check table schema first before doing anything

**Comment by davalapar** [comment]
See #8
